//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ClassLibrary1
{
    public partial class Employee
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string MailAddress { get; set; }
    
        public virtual Department Department { get; set; }
    }
    
}
